### ISSUE TITLE
im having issues making it run

### ISSUE THREAD

**Issue by tavionte** [oatsu-gh/ENUNU#6]
![help](https://user-images.githubusercontent.com/17653168/124336418-9b60f500-db63-11eb-9ac3-ee5d9a2d8ea4.PNG)

when I select the notes and run the plugin nothing happens.

**Comment by oatsu-gh** [comment]
## Firstly try
- You should install ENUNU models (ENUNU_夏目悠李_RMDN_v0.0.3.zip this case) by D&D into UTAU editor so that the models are installed into _username_\appdata\roaming\UTAU\voice\.

## If the problem does not solve
- UTAU should not be installed in C:\Program Files (x86) but should be installed in  C:\UTAU or D\:UTAU to avoid bugs.
-  I reccommend you to uninstall UTAU ind re-install it into C:\UTAU.
